---
title: "Classification Using Selected Mir and TF Medoids"
author: "Amir Asiaee"
date: '`r Sys.Date()`'
output:
  html_document:
    highlight: kate
    theme: yeti
    toc: yes
---

```{r globopt}
knitr:::opts_chunk$set(fig.path="../results/mirfigs/")
knitr::opts_chunk$set(fig.width=12) 
```

```{r mycss, results="asis", echo=FALSE}
cat('
<style type="text/css">
b, strong {color: red; }
i, em {color: blue; }
.defn {color: purple; }
.para {color: purple;
      font-weight: bold;
}
.figure { text-align: center; }
.caption { font-weight: bold; }
</style>
')
```

# Getting Started
Here, the goal is to show that the selected features (TFs and miRs), preserve biology. We show that we can use these small number of features (under 50) to classify cancer types. 

```{r , warning=FALSE}
rm(list=ls())
source("00-paths.R")

load(file.path(paths$clean, 'xena-tcga.Rda'))
load(file.path(paths$scratch, "xena-tcga-mir-medoid.Rda"))
load(file.path(paths$scratch, "xena-tcga-tf-medoid.Rda"))


cancerType <- as.factor(tcga$tissue)
nCT <- length(unique(cancerType))
cohortColor <- cohorts$color
names(cohortColor) <- rownames(cohorts)

X1 <- as.data.frame(cbind(tfMedoid, mirMedoid))
X <- data.frame(X1, ctype = cancerType)

dim(mirMedoid)
dim(tfMedoid)

rm(tcga, mirMedoid, tfMedoid, cohorts)
```

# Classification

```{r , warning = FALSE, echo=FALSE}
suppressMessages(library(viridis))
suppressMessages(library(e1071))
suppressMessages(library(caret))
suppressMessages(library(ComplexHeatmap))

f <- file.path(paths$scratch, 'xena-cv-SVM.rda')
if(file.exists(f)){
  load(f)
} else {
  set.seed(123)
  nfolds <- 10
  nTrain <- nrow(X)
  medSvmList <- pmedSvmList <- cfmedSvmList <- list()
  foldsId <- sample(rep(1:nfolds, length.out = nTrain), replace = F)
  cfmedSvmMean <- matrix(0, nrow=nCT, ncol=nCT)
  for (k in 1:nfolds) {
    print(paste("Fold", k, "started."))
    testId <- which(foldsId == k)
    train <- X[-testId, ]; 
    test <- X[testId, ];
    
    medSvm <- svm(ctype ~ ., train)
    pmedSvm <- predict(medSvm, test[,-ncol(test)])
    cfmedSvm <- confusionMatrix(pmedSvm, test$ctype)
    print(cfmedSvm$overall['Accuracy'])
  
    medSvmList[[k]] <- medSvm
    pmedSvmList[[k]] <- pmedSvm
    cfmedSvmList[[k]] <- cfmedSvm
    temp <- as.data.frame.matrix(cfmedSvm$table)
    cfmedSvmMean <- cfmedSvmMean + as.matrix(temp)
  }
  cfmedSvmMean <- cfmedSvmMean / nfolds
  cat("Average Accuracy:", mean(sapply(cfmedSvmList, function(x) x$overall['Accuracy'])))
  save(cfmedSvmMean, medSvmList, pmedSvmList, cfmedSvmList, file = f)
}

# res <- 300
# png(file=file.path(paths$figures, 'classification.png'),
#            width=16*res, height=9*res, res=res, bg="white")
# tempM <- cfmedSvmMean
# diag(tempM) <- NA
# heatmap(as.table(tempM), Rowv=NA, Colv = NA, col=viridis(256), main = "Average Confusion Matrix for 10-fold Cross Validation", scale = 'none')
# dev.off()
#   
# cat("Average Accuracy:", mean(sapply(cfmedSvmList, function(x) x$overall['Accuracy'])))

outputDir <- file.path(paths$clean, 'figures-tpm') 
if (!dir.exists(outputDir)) 
  dir.create(outputDir)

# res <- 300
# png(file=file.path(outputDir, 'classification-tpm.png'),
#     width=10*res, height=10*res, res=res, bg="white")  # Make the canvas square

library(gplots)

# Your provided code to create the normalized confusion matrix:
confusion_matrix_norm <- sweep(cfmedSvmMean, 1, rowSums(cfmedSvmMean), FUN = "/")
tempM <- confusion_matrix_norm
diag(tempM) <- NA

# Adjust plotting parameters for title distance
par(mai=c(0.7,0.7,0.5,0.5)) # adjust margin for title distance

# Using heatmap.2 to create the heatmap
heatmap.2(tempM,
          main = "Average Confusion Matrix for 10-fold Cross Validation",
          trace = "none", # Removes trace lines
          dendrogram = "none", # No clustering dendrogram
          Rowv = NA, # No row clustering
          Colv = NA, # No column clustering
          col = viridis(256), # Color scheme
          scale = "none", # No scaling
          key = FALSE, # Remove color key
          margins = c(5, 5), # Set margins
          cellnote = round(tempM * 100, 0), # Multiply by 100 and add to cell annotations
          notecol = "black", # Color of the cell annotations
          lhei = c(1, 4), # Adjust the height ratio to make the heatmap more square
          lwid = c(1, 4)) # Adjust the width ratio to make the heatmap more square

# Reset plotting parameters to default
par(mai=c(1,1,1,1))

# dev.off()


rm(cfmedSvm,cfmedSvmList, cfmedSvmMean, medSvm, medSvmList, pmedSvm, pmedSvmList, 
   tempM, test, res, train, foldsId, k, nfolds, nTrain, testId)

# rm(mirMedoid, tfMedoid, temp)
```


# Visualization

```{r , warning = FALSE}
medSvm <- svm(ctype ~ ., X)
pmedSvm <- predict(medSvm, X)
cfmedSvm <- confusionMatrix(pmedSvm, X$ctype)
print(cfmedSvm$overall)
colvec1 <- cohortColor[as.character(pmedSvm)]

library(Rtsne)
library(viridis)

# Standardize the data
X1 <- scale(X1)

colvec <- cohortColor[as.character(cancerType)]
set.seed(42)
cancers <- Rtsne(X1, perplexity = 30, learning_rate = 500, initial_dims = 60)

xcent <- tapply(cancers$Y[,1], list(cancerType), median)
ycent <- tapply(cancers$Y[,2], list(cancerType), median)

# Plotting the t-SNE results
# res <- 300
# png(file=file.path(outputDir, paste0("classification-tsne.png")),
#        width=16*res, height=9*res, res=res, bg="white")
par(mfrow=c(1,2))

plot(cancers$Y, col=colvec, xlab="T1", ylab="T2", cex=0.8, main="Ground Truth")
text(xcent, ycent, levels(cancerType), col='black', cex=1.5)


colvec2 <- rep(viridis(5)[3], length(colvec1))
colvec2[colvec != colvec1] <- viridis(5)[5]
plot(cancers$Y, col=colvec2, xlab="T1", ylab="T2", cex=0.8, main="Classification")
rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4], col = "lavender")
par(new = TRUE)
plot(cancers$Y, col=colvec2, xlab="T1", ylab="T2", cex=0.8, main="Classification")
text(xcent, ycent, levels(cancerType), col='black', cex=1.5)
dev.off()


# par(mfrow=c(1,1))

rm(cancers, cfmedSvm, medSvm, colvec, colvec1, colvec2, pmedSvm, res, xcent, ycent)
```

# Appendix

This analysis was performed using the following R packages.
```{r si}
sessionInfo()
```




